### ISSUE TITLE
How do we handle Avro Unions?

### ISSUE THREAD

**Issue by metasim** [s22s/avro2spark#1]
Spark `StructType`s don't support unions (as best I can tell). The type to select is dependent upon the value of the object to convert (yay, it's a dependent type!). 

Hack is to pass the buck with [a hook](https://github.com/s22s/avro2spark/blob/master/src/main/scala/astraea/demo/HijackAvro.scala#L68), but it's not satisfying nor likely powerful enough.

What other options do we have here?

CC: @pomadchin @mteldridge @lossyrob @echeipesh

**Comment by pomadchin** [comment]
@metasim ~~can you provide more context? (pseudo)code example? (how it should look like / your thoughts)~~ looked through code, problem is clear.

**Comment by pomadchin** [comment]
there is an interesting project: https://github.com/databricks/spark-avro

section: https://github.com/databricks/spark-avro#supported-types-for-avro---spark-sql-conversion

https://github.com/databricks/spark-avro/blob/branch-3.1/src/main/scala/com/databricks/spark/avro/SchemaConverters.scala#L44

**Comment by echeipesh** [comment]
Well, thats very convenient. Looks like we can use GT Avro codecs to `RDD[(K, V)] => RDD[Array[Byte]]` and use avro-spark to take it `RDD[Array[Byte]] => Dataset[Row]` given that @pomadchin showed how to convert the schema.
